name: /dev/lawyer
description: law, technology, and the space between
url: https://writing.kemitchell.com
permalink: :year/:month/:day/:title.html
author: Kyle E. Mitchell
homepage: https://kemitchell.com
highlighter: rouge
excerpt_separator: "<!--jump-->"
repository: kemitchell/writing.kemitchell.com
repository_url: "https://github.com/kemitchell/writing.kemitchell.com"
subscribe_url: "mailto:subscribe@kemitchell.com?subject=Subscribe%20to%20Blog"
plugins:
- jekyll-sass-converter
- jekyll-feed
feed:
  path: atom.xml
exclude:
- vendor
- Gemfile
- Gemfile.lock
- Makefile
- listtags
defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
