name: /dev/lawyer
description: Law, technology, and the space between
url: https://writing.kemitchell.com
permalink: :year/:month/:day/:title.html
author: Kyle E. Mitchell
homepage: https://kemitchell.com
highlighter: rouge
excerpt_separator: "<!--jump-->"
repository: kemitchell/writing
repository_url: "https://github.com/kemitchell/writing"
gems:
- jekyll-sass-converter
- jekyll-feed
exclude:
- vendor
